# 将静态内容部署到GitHub Pages
name: 将网站部署到Github页面

on:
  #在针对默认分支的推送上运行
  push:
    branches: ["main"]

  # 允许从“操作”选项卡手动运行此工作流
  workflow_dispatch:

# 设置GITHUB_TOKEN的权限以允许部署到GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

#只允许一个并发部署，跳过正在进行的运行和最近排队的运行之间的排队。
#但是不要取消正在进行的。
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  #单个部署作业，因为只部署
  deploy:
    environment:
      name: github页面
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: 完成
        uses: actions/checkout@v4
      - name: 设置网站
        uses: actions/configure-pages@v5
      - name: 上传对象
        uses: actions/upload-pages-artifact@v3
        with:
          #上传整个仓库
          path: '.'
      - name: 部署到GitHub页面
        id: deployment
        uses: actions/deploy-pages@v4
